AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Evn:
    Type: String
  Prefix:
    Type: String   

Resources:
# VPC Create
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.5.0.0/16'
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}-${Evn}-vpc"
        - Key: Project
          Value: !Ref Prefix
# Public SubnetA Create
  PublicSubnetA: 
    Type: "AWS::EC2::Subnet"
    Properties: 
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: '10.5.10.0/24'
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${Prefix}-${Evn}-public-subnet-a"
         
# InternetGateway Create
  InternetGateway: 
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: Name
          Value: !Sub "${Prefix}-${Evn}-igw"          