AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Prefix:
    Type: String
  VPCcidr:
    Type: String    
  PublicSubnetACIDR:
    Type: String

Resources:
# VPC Create
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCcidr
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}-vpc"
        - Key: Project
          Value: !Ref Prefix
# Public SubnetA Create
  PublicSubnetA: 
    Type: "AWS::EC2::Subnet"
    Properties: 
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: !Ref PublicSubnetACIDR
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Sub "${Prefix}-public-subnet-a"
         
# InternetGateway Create
  InternetGateway: 
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: Name
          Value: !Sub "${Prefix}-igw"          