AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Prefix:
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.4.0.0/16'
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}-vpc-develop"
        - Key: Project
          Value: !Sub "${Prefix}-pj-develop"